# Generated by Django 5.2.8 on 2025-11-20 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=50, unique=True, verbose_name='ລະຫັດບາໂຄດ')),
                ('name', models.CharField(max_length=200, verbose_name='ຊື່ອາໄຫຼ່')),
                ('description', models.TextField(blank=True, null=True, verbose_name='ລາຍລະອຽດ')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ຕົ້ນທຶນ')),
                ('sell_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ລາຄາຂາຍ')),
                ('quantity', models.IntegerField(default=0, verbose_name='ຈຳນວນຄົງເຫຼືອ')),
            ],
            options={
                'verbose_name': 'ສິນຄ້າ',
                'verbose_name_plural': 'ຂໍ້ມູນສິນຄ້າທັງໝົດ',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('IN', 'ນຳເຂົ້າ (ຊື້)'), ('OUT', 'ຂາຍອອກ')], max_length=3, verbose_name='ປະເພດ')),
                ('amount', models.IntegerField(verbose_name='ຈຳນວນ')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='ມູນຄ່າລວມ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ວັນເວລາ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='ສິນຄ້າ')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ຜູ້ເຮັດລາຍການ')),
            ],
            options={
                'verbose_name': 'ປະຫວັດການເຄື່ອນໄຫວ',
                'verbose_name_plural': 'ປະຫວັດການເຄື່ອນໄຫວ',
            },
        ),
    ]
