# Generated by Django 5.0.6 on 2025-11-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ໝວດໝູ່"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="products/", verbose_name="ຮູບພາບ"
            ),
        ),
    ]
