# Generated by Django 5.0.6 on 2025-11-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_product_category_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=250, unique=True, verbose_name="URL Slug"
            ),
        ),
    ]
