# Generated by Django 5.2.8 on 2025-11-20 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ຊື່ຍີ່ຫໍ້')),
                ('image', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='ໂລໂກ້')),
            ],
            options={
                'verbose_name': 'ຍີ່ຫໍ້',
                'verbose_name_plural': 'ຂໍ້ມູນຍີ່ຫໍ້ທັງໝົດ',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.brand', verbose_name='ຍີ່ຫໍ້'),
        ),
    ]
