# Generated by Django 5.2.8 on 2025-12-21 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_brand_product_brand'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=3, unique=True, verbose_name='ລະຫັດສະກຸນເງິນ')),
                ('name', models.CharField(max_length=50, verbose_name='ຊື່ສະກຸນເງິນ')),
                ('rate_to_thb', models.DecimalField(decimal_places=6, default=1.0, max_digits=15, verbose_name='ອັດຕາແລກປ່ຽນທຽບກັບ THB')),
                ('symbol', models.CharField(max_length=5, verbose_name='ສັນຍາລັກ')),
            ],
            options={
                'verbose_name': 'ອັດຕາແລກປ່ຽນ',
                'verbose_name_plural': 'ຈັດການອັດຕາແລກປ່ຽນ',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=20, unique=True, verbose_name='ເລກທີບິນ')),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='ຊື່ລູກຄ້າ')),
                ('customer_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='ເບີໂທ')),
                ('car_register_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='ທະບຽນລົດ')),
                ('car_province', models.CharField(blank=True, max_length=100, null=True, verbose_name='ແຂວງ')),
                ('car_brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='ຍີ່ຫໍ້ລົດ')),
                ('car_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='ລຸ້ນ')),
                ('car_frame_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='ເລກຖັງ')),
                ('car_mileage', models.CharField(blank=True, max_length=50, null=True, verbose_name='ເລກ ກມ')),
                ('car_colour', models.CharField(blank=True, max_length=50, null=True, verbose_name='ສີ')),
                ('mechanic_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='ຊ່າງສ້ອມ')),
                ('sale_representative', models.CharField(blank=True, max_length=200, null=True, verbose_name='ພະນັກງານຂາຍ')),
                ('subtotal_thb', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('discount_thb', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_amount_thb', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_amount_thb', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('rate_lak', models.DecimalField(decimal_places=6, default=1, max_digits=15)),
                ('rate_usd', models.DecimalField(decimal_places=6, default=1, max_digits=15)),
                ('net_amount_lak', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('net_amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='ໝາຍເຫດ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ວັນທີອອກບິນ')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ຜູ້ຂາຍ')),
            ],
            options={
                'verbose_name': 'ບິນການຂາຍ',
                'verbose_name_plural': 'ລາຍການບິນທັງໝົດ',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price_thb', models.DecimalField(decimal_places=2, max_digits=15)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_amount_thb', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount_thb', models.DecimalField(decimal_places=2, max_digits=15)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
            ],
        ),
    ]
