# Generated by Django 5.2.8 on 2025-12-21 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_currencyrate_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='ລະຫັດລູກຄ້າ')),
                ('name', models.CharField(max_length=200, verbose_name='ຊື່ລູກຄ້າ')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='ເບີໂທ')),
                ('car_register_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='ທະບຽນລົດ')),
                ('car_province', models.CharField(blank=True, max_length=100, null=True, verbose_name='ແຂວງ')),
                ('car_brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='ຍີ່ຫໍ້ລົດ')),
                ('car_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='ລຸ້ນ')),
                ('car_frame_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='ເລກຖັງ')),
                ('car_colour', models.CharField(blank=True, max_length=50, null=True, verbose_name='ສີ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ຂໍ້ມູນລູກຄ້າ',
                'verbose_name_plural': 'ຂໍ້ມູນລູກຄ້າທັງໝົດ',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer', verbose_name='ລູກຄ້າ'),
        ),
    ]
