# Generated by Django 5.2.8 on 2025-12-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_customer_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ໜ່ວຍ'),
        ),
    ]
