# Generated by Django 5.2.8 on 2025-12-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_orderitem_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ສາຂາ'),
        ),
        migrations.AddField(
            model_name='order',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ທະນາຄານ'),
        ),
        migrations.AddField(
            model_name='order',
            name='check_date',
            field=models.DateField(blank=True, null=True, verbose_name='ວັນທີໃນເຊັກ'),
        ),
        migrations.AddField(
            model_name='order',
            name='check_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ເລກທີເຊັກ'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_amount_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ເງິນສົດ'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_amount_check',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ເຊັກທະນາຄານ'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_amount_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ຕຶດໜີ້'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ວິທີຈ່າຍເງິນ'),
        ),
        migrations.AddField(
            model_name='order',
            name='received_by',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ຜູ້ຮັບເງິນ'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ref_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ລະຫັດສິນຄ້າ'),
        ),
    ]
