# Generated by Django 5.2.8 on 2025-12-22 02:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_bank_branch_order_bank_name_order_check_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'ບິນ', 'verbose_name_plural': 'ບິນທັງໝົດ'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['item_no'], 'verbose_name': 'ລາຍການສິນຄ້າ', 'verbose_name_plural': 'ລາຍການສິນຄ້າທັງໝົດ'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='car_colour',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='discount_amount_thb',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='total_amount_thb',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='unit_price_thb',
        ),
        migrations.AddField(
            model_name='order',
            name='car_color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ສີລົດ'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ລະຫັດລູກຄ້າ'),
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='ວັນທີ'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_lak',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ສ່ວນຫຼຸດລວມ (LAK)'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ສ່ວນຫຼຸດລວມ (USD)'),
        ),
        migrations.AddField(
            model_name='order',
            name='good_received_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ຜູ້ຮັບສິນຄ້າ'),
        ),
        migrations.AddField(
            model_name='order',
            name='good_received_by_date',
            field=models.DateField(blank=True, null=True, verbose_name='ວັນທີຜູ້ຮັບສິນຄ້າ'),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ຜູ້ຈ່າຍເງິນ'),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_by_date',
            field=models.DateField(blank=True, null=True, verbose_name='ວັນທີຜູ້ຈ່າຍເງິນ'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_cash',
            field=models.BooleanField(default=False, verbose_name='ເງິນສົດ'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_check',
            field=models.BooleanField(default=False, verbose_name='ເຊັກທະນາຄານ'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_credit',
            field=models.BooleanField(default=False, verbose_name='ເຄຣດິດ/ຕິດໜີ້'),
        ),
        migrations.AddField(
            model_name='order',
            name='received_by_date',
            field=models.DateField(blank=True, null=True, verbose_name='ວັນທີຜູ້ຮັບເງິນ'),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal_lak',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ຍອດລວມ (LAK)'),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ຍອດລວມ (USD)'),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_amount_lak',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ຈຳນວນອາກອນ (LAK)'),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_amount_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ຈຳນວນອາກອນ (USD)'),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='ອັບເດດເມື່ອ'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ຈຳນວນເງິນລວມ'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='ສ້າງເມື່ອ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ຈຳນວນສ່ວນຫຼຸດ'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_no',
            field=models.IntegerField(default=1, verbose_name='ລຳດັບ'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ລາຄາຕໍ່ໜ່ວຍ'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='ອັບເດດເມື່ອ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ສາຂາ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ທະນາຄານ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='car_frame_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ເລກຊາສີ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='car_mileage',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ເລກ km'),
        ),
        migrations.AlterField(
            model_name='order',
            name='car_model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ແບບລົດ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='car_register_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ທະບຽນລົດ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ສ້າງເມື່ອ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ເບີໂທລະສັບລູກຄ້າ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_thb',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ສ່ວນຫຼຸດລວມ (THB)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_no',
            field=models.CharField(max_length=50, unique=True, verbose_name='ເລກທີບິນ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='mechanic_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ຊ່າງສ້ອມ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='net_amount_lak',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ລວມສຸດທິ (LAK)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='net_amount_thb',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ລວມສຸດທິ (THB)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='net_amount_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ລວມສຸດທິ (USD)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_amount_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ຈຳນວນເງິນສົດ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_amount_check',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ຈຳນວນເງິນເຊັກ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_amount_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ຈຳນວນເງິນເຄຣດິດ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='received_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ຜູ້ຮັບເງິນ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sale_representative',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ພະນັກງານຂາຍ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal_thb',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ຍອດລວມ (THB)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax_amount_thb',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ຈຳນວນອາກອນ (THB)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='ອາກອນ %'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='description',
            field=models.TextField(verbose_name='ລາຍການ'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='ສ່ວນຫຼຸດ %'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order', verbose_name='ບິນ'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='ຈຳນວນ'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit',
            field=models.CharField(default='ອັນ', max_length=50, verbose_name='ໜ່ວຍ'),
        ),
    ]
