# Generated by Django 5.2.8 on 2025-12-22 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='car_colour',
            new_name='car_color',
        ),
    ]
