# Generated by Django 5.2.8 on 2025-12-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_car_colour_customer_car_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='car_mileage',
            field=models.IntegerField(default=0, verbose_name='ເລກກິໂລ (km)'),
        ),
    ]
