# Generated by Django 5.2.8 on 2025-12-22 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_customer_car_mileage'),
    ]

    operations = [
    ]
