# Generated by Django 5.2.8 on 2025-12-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_old_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ຊື່ໝວດໝູ່')),
                ('description', models.TextField(blank=True, null=True, verbose_name='ລາຍລະອຽດ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='ຮູບພາບ')),
            ],
            options={
                'verbose_name': 'ໝວດໝູ່',
                'verbose_name_plural': 'ຂໍ້ມູນໝວດໝູ່ທັງໝົດ',
            },
        ),
    ]
