# Generated by Django 5.2.8 on 2025-12-22 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_convert_category_to_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_str',
        ),
    ]
