# Generated by Django 5.2.8 on 2025-12-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_product_category_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mechanic_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ຊ່າງສ້ອມ'),
        ),
        migrations.AddField(
            model_name='customer',
            name='sale_representative',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ພະນັກງານຂາຍ'),
        ),
    ]
