# Generated by Django 5.2.8 on 2026-01-26 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_cashbook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CashBook',
        ),
    ]
