# Generated by Django 5.2.9 on 2026-01-27 00:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_delete_cashbook'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_no', models.CharField(max_length=50, unique=True, verbose_name='ເລກທີໃບສະເໜີລາຄາ')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='ວັນທີ')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='ໃຊ້ໄດ້ເຖິງວັນທີ')),
                ('status', models.CharField(choices=[('DRAFT', 'ຮ່າງ (Draft)'), ('SENT', 'ສົ່ງແລ້ວ (Sent)'), ('ACCEPTED', 'ລູກຄ້າຕົກລົງ (Accepted)'), ('REJECTED', 'ປະຕິເສດ (Rejected)'), ('CONVERTED', 'ສ້າງບິນແລ້ວ (Converted)')], default='DRAFT', max_length=20, verbose_name='ສະຖານະ')),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='ຊື່ລູກຄ້າ')),
                ('customer_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='ເບີໂທລະສັບລູກຄ້າ')),
                ('car_register_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='ທະບຽນລົດ')),
                ('car_brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='ຍີ່ຫໍ້ລົດ')),
                ('car_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='ແບບລົດ')),
                ('car_mileage', models.CharField(blank=True, max_length=50, null=True, verbose_name='ເລກ km')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ຍອດລວມ')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ສ່ວນຫຼຸດ')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ອາກອນ')),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ຍອດລວມສຸດທິ')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='ໝາຍເຫດ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ສ້າງເມື່ອ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ອັບເດດເມື່ອ')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer', verbose_name='ລູກຄ້າ')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ຜູ້ອອກໃບ')),
            ],
            options={
                'verbose_name': 'ໃບສະເໜີລາຄາ',
                'verbose_name_plural': 'ໃບສະເໜີລາຄາທັງໝົດ',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.IntegerField(default=1, verbose_name='ລຳດັບ')),
                ('description', models.TextField(verbose_name='ລາຍການ')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='ຈຳນວນ')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ລາຄາຕໍ່ໜ່ວຍ')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ຈຳນວນເງິນລວມ')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.quotation', verbose_name='ໃບສະເໜີລາຄາ')),
            ],
            options={
                'verbose_name': 'ລາຍການສະເໜີລາຄາ',
                'verbose_name_plural': 'ລາຍການສະເໜີລາຄາ',
                'ordering': ['item_no'],
            },
        ),
    ]
