# Generated by Django 5.2.8 on 2026-01-26 08:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0019_delete_cashbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='ວັນທີ')),
                ('time', models.TimeField(default=django.utils.timezone.now, verbose_name='ເວລາ')),
                ('description', models.CharField(max_length=255, verbose_name='ລາຍການ')),
                ('transaction_type', models.CharField(choices=[('IN', 'ລາຍຮັບ (Income)'), ('OUT', 'ລາຍຈ່າຍ (Expense)')], max_length=3, verbose_name='ປະເພດ')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='ຈຳນວນເງິນ')),
                ('category', models.CharField(blank=True, help_text='ຕົວຢ່າງ: ຄ່າອາຫານ, ຄ່າຂົນສົ່ງ, ຂາຍສິນຄ້າ ໜ້າຮ້ານ', max_length=100, null=True, verbose_name='ໝວດໝູ່')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order', verbose_name='ບິນອ້າງອີງ')),
            ],
            options={
                'verbose_name': 'ບັນຊີລາຍຮັບ-ລາຍຈ່າຍ',
                'verbose_name_plural': 'ບັນຊີລາຍຮັບ-ລາຍຈ່າຍ',
                'ordering': ['-date', '-time', '-created_at'],
            },
        ),
    ]
