# Generated by Django 5.2.8 on 2026-01-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbook',
            name='currency',
            field=models.CharField(choices=[('LAK', 'LAK - ກີບ (₭)'), ('THB', 'THB - ບາດ (฿)'), ('USD', 'USD - ໂດລາ ($)')], default='LAK', max_length=3, verbose_name='ສະກຸນເງິນ'),
        ),
    ]
